Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from osipi_code_collection.wrappers.vfa import vfa_fit, show_maps, show_error_maps
from osipi_code_collection.utils.nb import download_osf, loadmat

vfafile = "./data/vfadata.mat"
download_osf("https://osf.io/jzu4k/download", vfafile)
vfadata = loadmat(vfafile)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01mwrappers[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvfa[39;00m [38;5;28;01mimport[39;00m vfa_fit, show_maps, show_error_maps
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnb[39;00m [38;5;28;01mimport[39;00m download_osf, loadmat
[1;32m      4[0m vfafile [38;5;241m=[39m [38;5;124m"[39m[38;5;124m./data/vfadata.mat[39m[38;5;124m"[39m

File [0;32m/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/osipi_code_collection/wrappers/vfa.py:2[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01moriginal[39;00m[38;5;21;01m.[39;00m[38;5;21;01mMJT_UoEdinburgh_UK[39;00m[38;5;21;01m.[39;00m[38;5;21;01mt1_fit[39;00m [38;5;28;01mas[39;00m [38;5;21;01medinburgh[39;00m
[0;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01moriginal[39;00m[38;5;21;01m.[39;00m[38;5;21;01mST_USydAUS[39;00m[38;5;21;01m.[39;00m[38;5;21;01mVFAT1mapping[39;00m [38;5;28;01mas[39;00m [38;5;21;01msydney[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01moriginal[39;00m[38;5;21;01m.[39;00m[38;5;21;01mMcGill_CAN[39;00m[38;5;21;01m.[39;00m[38;5;21;01mvfa[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmcgill[39;00m
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mosipi_code_collection[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnb[39;00m [38;5;28;01mimport[39;00m percenterror

[0;31mModuleNotFoundError[0m: No module named 'osipi_code_collection.original.ST_USydAUS'

